Create strings
h
ello
hellohello
5
Traceback (most recent call last):
  File "/home/main.py", line 12, in <module>
    str1[0]='H'
TypeError: 'str' object does not support item assignment